name = "geminipocket"
main = "build/worker/shim.mjs"
compatibility_date = "2024-12-01"

[build]
command = "./build.sh"

[[d1_databases]]
binding = "DB"
database_name = "geminipocket"
database_id = "5813adae-ad9d-4560-940e-f48ed91c103b"

[vars]

[env.production]
name = "geminipocket-production"

[env.staging]
name = "geminipocket-staging"