name = "geminipocket"
main = "build/worker/shim.mjs"
compatibility_date = "2024-01-01"

[build]
command = "cargo install -q worker-build && ~/.cargo/bin/worker-build --release"

[vars]
TEST_MODE = "true"

[[d1_databases]]
binding = "DB"
database_name = "geminipocket_db"
database_id = "your-database-id-here"